---

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Generic Event Webhook 
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name: DEMO-UI -      ðŸ‘“ Load parameters
  include_vars: ../00_config_cp4waiops.yaml




- name: DEMO-UI -      ðŸš€ Create CP4WAIOPS Demo UI  
  community.kubernetes.k8s:
    state: present
    template: ./templates/waiops-demo-ui/create-cp4waiops-demo.j2
