#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
#  CP4WAIOPS 3.2 - Ansible Install Parameters
#
#  CloudPak for Watson AIOps
#
#  Â©2021 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# OCP LOGIN PARAMETERS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
OCP_LOGIN: false
OCP_URL: not_configured
OCP_TOKEN: not_configured

#Version of your OCP Cluster (override by setting manually - 4.6, 4.7,...)
OCP_MAJOR_VERSION: automatic




# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS INSTALL PARAMETERS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# CP4WAIOPS Namespace for installation
WAIOPS_NAMESPACE: cp4waiops

# CP4WAIOPS Size of the install (small: PoC/Demo, tall: Production)
WAIOPS_SIZE: small # Leave at small unless you know what you're doing

# Install standalone Netcool Oprations Insight
INSTALL_NOI: false
# CP4WAIOPS Namespace for installation
NOI_NAMESPACE: noi

# Override the Storage Class auto detection
STORAGECLASS_FILE_OVERRIDE: not_configured
STORAGECLASS_BLOCK_OVERRIDE: not_configured

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# DEMO INSTALL PARAMETERS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# Create a demo user in the OCP cluster
CREATE_DEMO_USER: true

# Install Demo Applications
INSTALL_DEMO_APPS: true

# Print all credentials at the end of the installation
PRINT_LOGINS: true

# Install Bastion Server for Runbook Automation
INSTALL_RUNBOOK_BASTION: true

# Should Rook-Ceph be installed (automatic: install when on IBM Fyre) (enable, automatic, disable)
ROOK_CEPH_INSTALL_MODE: automatic


# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# MODULE INSTALL PARAMETERS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


# Install LDAP Server
INSTALL_LDAP: true

# Install Turbonomic (experimental - needs separate license)
INSTALL_TURBONOMIC: false
# Turbonomic Storage Class (ibmc-block-gold, rook-cephfs, nfs-client, ...)
STORAGE_CLASS_TURBO: ibmc-block-gold
# Install Turbonomic Metrics simulation (highly experimental!)
INSTALL_TURBONOMIC_METRICS: false
# Install Turbonomic --> NOI Gateway (highly experimental!)
INSTALL_TURBONOMIC_GATEWAY: false


# Install Humio (needs separate license)
INSTALL_HUMIO: false

# Install ELK Stack
INSTALL_ELK: false

# Install AWX (Open Source Ansible Tower)
INSTALL_AWX: false

# Install ManageIQ (Open Source CloudForms)
INSTALL_MANAGEIQ: false

# *************************************************************************************************************************************************
# *************************************************************************************************************************************************
# *************************************************************************************************************************************************
# DO NOT EDIT BELOW
# *************************************************************************************************************************************************
# *************************************************************************************************************************************************
# *************************************************************************************************************************************************



























































# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# WAIOPS Storage Classes
# The definite Storage class will be automatically determined!!!
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# CP4WAIOPS default Storage Class (ibmc-file-gold-gid, rook-cephfs, nfs-client, ...)
#WAIOPS_STORAGE_CLASS_FILE: ibmc-file-gold-gid         # ROKS
#WAIOPS_STORAGE_CLASS_FILE: rook-cephfs               # FYRE
#WAIOPS_STORAGE_CLASS_FILE: nfs-client                # TEC


# CP4WAIOPS default Large Storage Class (ibmc-file-gold-gid, rook-cephfs, nfs-client, ...)
#WAIOPS_STORAGE_CLASS_LARGE_BLOCK: ibmc-file-gold-gid  # ROKS
#WAIOPS_STORAGE_CLASS_LARGE_BLOCK: rook-cephfs        # FYRE
#WAIOPS_STORAGE_CLASS_LARGE_BLOCK: nfs-client         # TEC


# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# WAIOPS INSTALL PARAMETERS (do not change)
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
INSTALL_AIOPS: true
WAIOPS_NAME: ibm-aiops
CREATE_TOPO_ROUTE: true
CREATE_FLINK_ROUTE: true
CREATE_STRIMZI_ROUTE: true
INSTALL_GATEWAY: true
WAIOPS_NS_MIN_PODS_SECRET: 100
WAIOPS_NS_MIN_PODS_FINAL: 108
CS_NS_MIN_PODS: 35
ROOK_NS_MIN_PODS: 38
NOI_NS_MIN_PODS_FINAL: 70


# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# LDAP PARAMETERS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
LDAP_DOMAIN: ibm.com
LDAP_BASE: dc=ibm,dc=com
LDAP_ADMIN_PASSWORD: P4ssw0rd!















# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# IBM ENTITLED REGISTRY PARAMETERS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
ENTITLED_REGISTRY: cp.icr.io
ENTITLED_REGISTRY_USER: cp
ENTITLED_REGISTRY_KEY: TOKEN
SUBSCRIPTION_CHANNEL: v3.2


























# ENTITLED_REGISTRY: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com
# ENTITLED_REGISTRY_USER: nikh@ch.ibm.com

# CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.2.0-20211029.0822-d63ba3a42
#CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.2.0-20211022.0601-4c62759e2  <-- worked
#CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.2.0-20211017.0002-ec2d009bf   <-- worked
#CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.2.0-20211014.0401-744608902
#CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.2.0-20211011.1801-7097d5a87 <-- worked
#SUBSCRIPTION_CHANNEL: 3.2-dev

#CATALOG_IMAGE: icr.io/cpopen/aiops-orchestrator-catalog:3.2-latest



