
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install ADDONS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# --------------------------------------------------------------------------------------------------------------------------------------
# Install OpenLDAP
# --------------------------------------------------------------------------------------------------------------------------------------
# - name: ADDONS -             ‚ùé Remove old OpenLDAP
#   community.kubernetes.k8s:
#     state: absent
#     template: ./templates/ldap/install-ldap.j2
#   #when: INSTALL_LDAP == true

- name: LDAP -               üöÄ Install OpenLDAP
  community.kubernetes.k8s:
    state: present
    template: ./templates/ldap/install-ldap.j2
  #when: INSTALL_LDAP == true



