
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install CP4WAIOPS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

- name: CP4WAIOPS -          ðŸš€ Install Custom Resource - INSTALL AI MANAGER
  community.kubernetes.k8s:
    state: present
    template: './templates/waiops/4_waiops-install-template.j2'