---
# tasks file for aiops
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Ansible Install Playbook V0.1
#
#  CloudPak for Watson AIOps
#
#  Â©2021 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"


# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Get Config File
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name: PREREQUISITES -      ðŸ‘“ Load parameters
  include_vars: ../00_config_cp4waiops.yaml


# --------------------------------------------------------------------------------------------------------------------------------------
# --------------------------------------------------------------------------------------------------------------------------------------
# Install GENERAL PREREQUISITES
# --------------------------------------------------------------------------------------------------------------------------------------
# --------------------------------------------------------------------------------------------------------------------------------------

# Create Namespace 
- name: PREREQUISITES -      ðŸš€ Create CP4WAIOPS namespace {{ WAIOPS_NAMESPACE }}
  community.kubernetes.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ WAIOPS_NAMESPACE }}"
    state: present



# Patch OCP Registry
# - name: PREREQUISITES -      ðŸ©¹ Patch OCP Registry 
#   shell: oc patch configs.imageregistry.operator.openshift.io/cluster --patch '{"spec":{"defaultRoute":true}}' --type=merge
#   ignore_errors: yes



# # Create IBM Entitlements Pull Secret
# - name: PREREQUISITES -      ðŸ”Ž Check Pull Secret
#   k8s_info:
#     kind: Secret
#     name: ibm-entitlement-key
#     namespace: "{{ WAIOPS_NAMESPACE }}"
#   register: K8S_EXISTS
# - name: DEBUG -              ðŸŸ¢ Output
#   debug: 
#     var: K8S_EXISTS.resources
#     verbosity: 1


# Create IBM Entitlements Pull Secret
- name: PREREQUISITES -      ðŸš€ Create Pull Secret
  shell: |
    oc create secret docker-registry 'ibm-entitlement-key' --docker-server={{ ENTITLED_REGISTRY }} --docker-username={{ ENTITLED_REGISTRY_USER }} --docker-password={{ ENTITLED_REGISTRY_KEY }} --namespace={{ WAIOPS_NAMESPACE }}
    oc create secret docker-registry 'ibm-entitlement-key' --docker-server={{ ENTITLED_REGISTRY }} --docker-username={{ ENTITLED_REGISTRY_USER }} --docker-password={{ ENTITLED_REGISTRY_KEY }} --namespace=openshift-marketplace
    oc create secret docker-registry 'ibm-entitlement-key' --docker-server={{ ENTITLED_REGISTRY }} --docker-username={{ ENTITLED_REGISTRY_USER }} --docker-password={{ ENTITLED_REGISTRY_KEY }} --namespace=openshift-operators
    oc create secret docker-registry 'ibm-aiops-pull-secret' --docker-server={{ ENTITLED_REGISTRY }} --docker-username={{ ENTITLED_REGISTRY_USER }} --docker-password={{ ENTITLED_REGISTRY_KEY }} --namespace={{ WAIOPS_NAMESPACE }}
    oc create secret docker-registry 'ibm-aiops-pull-secret' --docker-server={{ ENTITLED_REGISTRY }} --docker-username={{ ENTITLED_REGISTRY_USER }} --docker-password={{ ENTITLED_REGISTRY_KEY }} --namespace=openshift-marketplace
    oc create secret docker-registry 'ibm-aiops-pull-secret' --docker-server={{ ENTITLED_REGISTRY }} --docker-username={{ ENTITLED_REGISTRY_USER }} --docker-password={{ ENTITLED_REGISTRY_KEY }} --namespace=openshift-operators
    oc patch -n openshift-marketplace serviceaccount ibm-aiops-catalog -p '{"imagePullSecrets": [{"name": "ibm-entitlement-key"}]}'
    oc patch -n openshift-marketplace serviceaccount default -p '{"imagePullSecrets": [{"name": "ibm-entitlement-key"}]}'
  ignore_errors: yes
  when: K8S_EXISTS.resources|length == 0


# Create aiops-topology-service-account
- name: PREREQUISITES -      ðŸš€ Create aiops-topology-service-account
  shell: |
    cat <<EOF | oc apply -n {{ WAIOPS_NAMESPACE }} -f -
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: aiops-topology-service-account
      labels:
        managedByUser: 'true'
    imagePullSecrets:
      - name: ibm-entitlement-key
    EOF
  ignore_errors: yes
  when: K8S_EXISTS.resources|length == 0


# Patch builder service account
# - name: PREREQUISITES -      ðŸ©¹ Patch builder service account
#   shell: |
#     INTERNAL=$(oc get secret -n {{ WAIOPS_NAMESPACE }} | grep '^builder-dockercfg' | cut -f1 -d ' ')
#     BASE=$(oc get secret ibm-entitlement-key -n {{ WAIOPS_NAMESPACE }} -o json | jq ".data[]" | sed -e 's/^"//' -e 's/"$//' | base64 -d | sed -e 's/}}$/,/')
#     ADDITIONAL=$(oc get secret $INTERNAL -n {{ WAIOPS_NAMESPACE }} -o json | jq ".data[]" | sed -e 's/^"//' -e 's/"$//' | base64 -d | sed -e 's/^{//')
#     echo $BASE$ADDITIONAL} > builder-secret.tmp
#     oc create secret generic merged-secret --type=kubernetes.io/dockerconfigjson --from-file=.dockerconfigjson=builder-secret.tmp -n {{ WAIOPS_NAMESPACE }} || true
#     rm builder-secret.tmp
#     oc patch serviceaccount builder  -p '{"secrets": [{"name": "merged-secret"}]}' -n {{ WAIOPS_NAMESPACE }} || true
#   register: ready
# - name: DEBUG -              ðŸŸ¢ Output
#   debug: 
#     var: ready.stdout_lines
#     verbosity: 1
