#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS 3.2
#
#  CloudPak for Watson AIOps
#
#  Â©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"


- hosts: localhost
  #become: true
  vars_files: ../00_config_cp4waiops.yaml

  roles:  
# Placeholder for customization
    - role: 00_pre


# Install Add-Ons while CP4WAIOPS is coming up
    - role: 25_aiops-addons-ldap
      when: INSTALL_LDAP


# Wait for Common Services being completely installed
    - role: 99_aiops-wait-common-services
      


# Post installation tasks
    - role: 40_aiops-post-ldap-register
      when: INSTALL_LDAP












