- name: TRAINING LOAD SNOW -       ðŸš€ LOAD ELASTICSEARCH SNOW DATA 
  kubernetes.core.k8s:
    state: present
    namespace: turbonomic
    src: ./templates/training/load-job-snow.yaml
  

- name: TRAINING LOAD SNOW -       ðŸ•¦ WAIT FOR COMPLETION
  shell: |
    while : ; do
          READY=$(oc get jobs -n default load-snow-indexes)
          if [[ ! $READY  =~ "1/1" ]]; then
                echo "        Load Job not completed. Waiting 30 seconds"
                sleep 30
          else
                break
          fi
    done
    echo "      âœ… OK"
  register: ES_READY



- name: TRAINING LOAD SNOW -       ðŸ§» CLEANUP JOB
  kubernetes.core.k8s:
    state: absent
    namespace: turbonomic
    src: ./templates/training/load-job-snow.yaml
  


- name: TRAINING LOAD SNOW -       ðŸ§» CLEANUP COMPLETED JOBS
  shell: |
    oc delete pod  -n default --ignore-not-found $(oc get po -n default|grep load-snow-indexes|awk '{print$1}')
  register: ES_READY
  ignore_errors: yes

