
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install ADDONS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# --------------------------------------------------------------------------------------------------------------------------------------
# Create OCP Demouser Account
# --------------------------------------------------------------------------------------------------------------------------------------
- name: USER -               ðŸ”Ž Check OCP Demouser Account
  k8s_info:
    kind: serviceaccount
    name: demo-admin
    namespace: default
  register: K8S_EXISTS

- name: USER -               ðŸ©¹ Create OCP Demouser Account
  shell: |
        oc project {{ WAIOPS_NAMESPACE }} 
        oc create serviceaccount -n default demo-admin
        oc create clusterrolebinding test-admin --clusterrole=cluster-admin --serviceaccount=default:demo-admin
        oc create clusterrolebinding ibm-zen-operator-serviceaccount --clusterrole=cluster-admin --serviceaccount=ibm-common-services:ibm-zen-operator-serviceaccount
  ignore_errors: yes
  register: demo_account
  when: K8S_EXISTS.resources|length == 0

